name: Continuous Deployment
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 44.220.53.10
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd cicd_testing
            git pull origin main
            pm2 delete all
            pnpm run build
            cd apps/web
            pm2 start npm --name "fe" -- start
            cd ..
            cd http-server
            pm2 start npm --name "http-server" -- start
            cd ..
            cd ws-server
            pm2 start npm --name "ws-server" -- start